<?php
/**
 *CreateBy:PhpStrom
 *User:youwei
 *Date:2022/6/13/013
 *Time:12:00
 */
class Notify {
    protected $color = "red";
    protected $credit = 10;
    public  function credit(){
        return 25;
    }
    public function message(){
        return '<span style="color:'. $this->color.'">欢迎您,您有'. $this->credit() ."个积分".'</span>';
    }
}

class User extends Notify {
    public function register(){
        echo $this->message();
    }

    // public  function credit(){         父类里的方法加上final，子类就不会覆盖，直接报错
    //     return 25;
    // }
}

class Comment extends Notify {
    public function send(){
        echo $this->message();
    }

    public function message()
    {
        // return 100;    在子类使用与父类方法相同方法，使用父类方法可以使用parent::
        //return parent::message(); // TODO: Change the autogenerated stub
    }
}

echo (new User())->register();
echo('<hr/>');
echo (new Comment())->send();